@startuml Comentar publicacion
[*] --> ViendoPublicacion : buscar publicacion
ViendoPublicacion --> ComentandoPublicacion : Seleccionar boton de comentar 
ComentandoPublicacion --> PublicacionComentada : publicar comentario
PublicacionComentada --> [*]
@enduml