@startuml Crear Evento
[*] --> GestionandoPublicacion : Pulsar boton crear publicacion
GestionandoPublicacion --> EsperandoPorAprobacionDeModerador : Creando evento
EsperandoPorAprobacionDeModerador --> [*]
@enduml