@startuml Campus Virtual Ciencias
class CampusVirtualCiencias
class Usuario{
    #username: string
    -password: string
    #email:string
    -cedula:int
    #rol:string
}
class Estudiante{
    #escuela: Escuela
    #carrera: string
}
class Profesor{
    #escuela: Escuela
    #titulo: string
}
class PersonalDeApoyo{
}
class PersonalTecnico{
}
class PersonalObrero{
}
class PersonalAdministrativo{
}
class Publicacion{
}
class PublicacionEstudiantil{
}
class PublicacionDocente{
}
class PublicacionDePersonalDeApoyo{
}
class PublicacionGrupoExtension{
}
class Comentario{
    #texto:string
}
class EventoInstitucional{
    #fecha:int
    #nombre:string
}
class ProyectoDocente{
}
class Investigacion{
}
class Taller{
}
class Seminario{
}
class GrupoDeEstudio{
}
class ActividadDeportiva{
}
class ActividadCultural{
}
class Escuela{
    #nombre:string
    #carreras:list
}
class Admin{
    #id:int
    -password: string
}
class GrupoDeExtension{
    #nombre:string
    #integrantes:list
    #description:string
}
class GrupoActividadDeportiva{
}
class GrupoActividadCultural{
}
class ModeradorDeGrupo{
}
class Calendario{
}
class GrupoDeEsparcimiento{
}
class ActividadEsparcimiento{
}
class FechaPublicacion {
}
class Notificacion {
}

CampusVirtualCiencias "1"  *-- "*" Publicacion : se estructura
Publicacion "1" *-- "n" Reaccion : tiene
Publicacion "1" *-- "n" Comentario : tiene 
Publicacion <|--PublicacionEstudiantil
Publicacion <|--PublicacionDocente
Publicacion <|--PublicacionDePersonalDeApoyo
Publicacion <|--PublicacionGrupoExtension
Usuario "*" -- "1" Publicacion : interacctuan
Estudiante "1" -- "*" PublicacionEstudiantil: Publica
Profesor "1" -- "*" PublicacionDocente: Publica
PersonalDeApoyo "1" -- "*" PublicacionDePersonalDeApoyo : publica
PublicacionEstudiantil <|-- Taller 
PublicacionEstudiantil <|-- Seminario 
PublicacionEstudiantil <|-- GrupoDeEstudio 
PublicacionGrupoExtension <|-- ActividadDeportiva 
PublicacionGrupoExtension <|-- ActividadCultural
PublicacionGrupoExtension <|-- ActividadEsparcimiento
Usuario <|-- Estudiante 
Usuario <|-- Profesor 
Usuario <|-- PersonalDeApoyo
PersonalDeApoyo <|-- PersonalTecnico
PersonalDeApoyo <|-- PersonalAdministrativo
PersonalDeApoyo <|-- PersonalObrero
PublicacionDocente <|-- ProyectoDocente
PublicacionDocente <|-- Investigacion
PublicacionDePersonalDeApoyo <|-- EventoInstitucional
CampusVirtualCiencias "1" *-- "*" Usuario : interactuan
Escuela "1" o-- "1" Estudiante
Escuela "1" o-- "1" Profesor
GrupoDeExtension "1" o-- "1 ... * " Estudiante : pertenece
Usuario <|-- Admin : puede ser
Estudiante <|-- ModeradorDeGrupo: puede ser
ModeradorDeGrupo "1..*" -- "1..*" GrupoDeExtension: modera
GrupoDeExtension <|-- GrupoActividadDeportiva 
GrupoDeExtension <|-- GrupoActividadCultural
GrupoActividadDeportiva "1" -- "1...*" ActividadDeportiva : publica
GrupoActividadCultural "1" -- "1...*" ActividadCultural : publica
Calendario "1" *-- "0..*" Publicacion : representa
Calendario "1" -- "1" Usuario : tiene
GrupoDeEsparcimiento "1" -- "1...*" ActividadEsparcimiento : publica
GrupoDeExtension <|-- GrupoDeEsparcimiento
CampusVirtualCiencias "1" *-- "1" Calendario : es parte de
Publicacion "1" *-- "1" FechaPublicacion : tiene
Publicacion "1" *-- "1"Notificacion : genera
Notificacion "1" -- "1...*" Usuario: informa 
@enduml